#!/usr/bin/env python3
"""Export the read-only showcase snapshot for the Vercel deploy.

One codebase, two data fidelities:
  - Local (127.0.0.1:3000): full mode, route handlers read the live DB/archive.
  - Vercel (SHOWCASE_MODE=1): showcase mode, route handlers serve the committed
    JSON fixtures (web/fixtures/*.json) + bundled images (web/public/showcase/*).

This script regenerates those committed artifacts from full local data. Run it
locally, then commit the result — "what's in git is what the Vercel site shows".

    python scripts/export_showcase.py

Step 1 (this skeleton): dump the landing-page fixtures via scripts/studio_cli.py.
TODO (step 2): export the per-session image subset (50 sessions x 5-10) into
    web/public/showcase/ — resize ~1440px, convert WebP, strip EXIF (incl. GPS).
TODO (step 3): freeze the full /infra console fixtures + per-session galleries.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
STUDIO_CLI = REPO_ROOT / "scripts" / "studio_cli.py"
FIXTURES_DIR = REPO_ROOT / "web" / "fixtures"

# (studio_cli command, extra args, fixture file name)
# Note: landing-gallery is intentionally NOT here — its fixture is tied to the
# bundled image subset and is (re)generated by the step-2 image export, not a
# plain CLI dump (the CLI needs a live export_dir that won't exist on a clean run).
LANDING_FIXTURES: list[tuple[str, list[str], str]] = [
    ("stats", [], "landing-stats"),
    ("landing-infra", [], "landing-infra"),
    ("landing-brain", [], "landing-brain"),
]


def run_cli(cmd: str, extra: list[str]) -> dict:
    """Invoke studio_cli.py <cmd> and parse its JSON stdout."""
    proc = subprocess.run(
        [sys.executable, str(STUDIO_CLI), cmd, *extra],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        timeout=120,
    )
    text = proc.stdout.strip()
    if not text:
        raise RuntimeError(f"studio_cli {cmd} produced no output\n{proc.stderr.strip()}")
    data = json.loads(text)
    if isinstance(data, dict) and data.get("error"):
        raise RuntimeError(f"studio_cli {cmd} error: {data['error']}")
    return data


def write_fixture(name: str, data: dict) -> None:
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    path = FIXTURES_DIR / f"{name}.json"
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"  ✓ {path.relative_to(REPO_ROOT)}")


def export_landing(dry_run: bool) -> int:
    print("Exporting landing fixtures from local data:")
    failed = 0
    for cmd, extra, name in LANDING_FIXTURES:
        try:
            data = run_cli(cmd, extra)
        except Exception as exc:  # noqa: BLE001 — surface, keep going
            print(f"  ✗ {name}: {exc}", file=sys.stderr)
            failed += 1
            continue
        if dry_run:
            print(f"  · {name}: {json.dumps(data, ensure_ascii=False)[:120]}…")
        else:
            write_fixture(name, data)
    return failed


def main() -> int:
    parser = argparse.ArgumentParser(description="Export the Vercel showcase snapshot.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be exported without writing fixtures.",
    )
    args = parser.parse_args()

    failed = export_landing(args.dry_run)

    # TODO(step 2): export_session_images(...) -> web/public/showcase/sessions/<sid>/*.webp
    # TODO(step 3): export_infra_console(...) -> web/fixtures/infra/*.json
    #               export_session_galleries(...) -> web/fixtures/sessions/<sid>.json

    if failed:
        print(f"\nDone with {failed} failure(s).", file=sys.stderr)
        return 1
    print("\nDone. Commit web/fixtures/ (and web/public/showcase/ once step 2 lands).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
