#!/usr/bin/env python3
"""Export the read-only showcase snapshot for the Vercel deploy.

One codebase, two data fidelities:
  - Local (127.0.0.1:3000): full mode, route handlers read the live DB/archive.
  - Vercel (SHOWCASE_MODE=1): showcase mode, route handlers serve the committed
    JSON fixtures (web/fixtures/*.json) + bundled images (web/public/showcase/*).

This script regenerates those committed artifacts from full local data. Run it
locally, then commit the result — "what's in git is what the Vercel site shows".

    python scripts/export_showcase.py

Per-session hero covers (one EXIF-stripped JPEG each) are built separately::

    python scripts/build_session_covers.py --src <heroes_dir> --count 9 --patch-fixtures

Those land in ``web/public/showcase/covers/session-NN.jpg`` and are referenced by
``cover_path_quoted`` in ``studio-sessions.json``. This exporter sets that field
to the public path (assets must already exist or be rebuilt before deploy).

TODO: optional multi-frame per-session gallery subset under web/public/showcase/.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

# Safety net: anything that still looks like a real local path / hostname after
# targeted anonymization gets neutralized here before a fixture is committed.
# We keep structural fields (incl. ``payload_json``, which the UI parses) but
# scrub any absolute path / ``.local`` hostname out of every string — including
# paths embedded inside JSON-encoded ``payload_json`` blobs.
_PATH_RES = [
    re.compile(r"/Volumes/[^\"'\s\\]+"),
    re.compile(r"/Users/[^\"'\s\\]+"),
]
_HOST_RE = re.compile(r"\b[\w-]+\.local\b")


def _scrub(obj):
    """Recursively neutralize any leaked absolute path / hostname in string values."""
    if isinstance(obj, dict):
        return {k: _scrub(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_scrub(v) for v in obj]
    if isinstance(obj, str):
        s = obj
        for rx in _PATH_RES:
            s = rx.sub("/archive/redacted", s)
        return _HOST_RE.sub("host.local", s)
    return obj

REPO_ROOT = Path(__file__).resolve().parents[1]
STUDIO_CLI = REPO_ROOT / "scripts" / "studio_cli.py"
FIXTURES_DIR = REPO_ROOT / "web" / "fixtures"

# (studio_cli command, extra args, fixture file name)
# Note: landing-gallery is intentionally NOT here — its fixture is tied to the
# bundled image subset and is (re)generated by the step-2 image export, not a
# plain CLI dump (the CLI needs a live export_dir that won't exist on a clean run).
LANDING_FIXTURES: list[tuple[str, list[str], str]] = [
    ("stats", [], "landing-stats"),
    ("landing-infra", [], "landing-infra"),
    ("landing-brain", [], "landing-brain"),
]


def run_cli(cmd: str, extra: list[str]) -> dict:
    """Invoke studio_cli.py <cmd> and parse its JSON stdout."""
    proc = subprocess.run(
        [sys.executable, str(STUDIO_CLI), cmd, *extra],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        timeout=120,
    )
    text = proc.stdout.strip()
    if not text:
        raise RuntimeError(f"studio_cli {cmd} produced no output\n{proc.stderr.strip()}")
    data = json.loads(text)
    if isinstance(data, dict) and data.get("error"):
        raise RuntimeError(f"studio_cli {cmd} error: {data['error']}")
    return data


def write_fixture(name: str, data: dict) -> None:
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)
    path = FIXTURES_DIR / f"{name}.json"
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"  ✓ {path.relative_to(REPO_ROOT)}")


def export_landing(dry_run: bool) -> int:
    print("Exporting landing fixtures from local data:")
    failed = 0
    for cmd, extra, name in LANDING_FIXTURES:
        try:
            data = run_cli(cmd, extra)
        except Exception as exc:  # noqa: BLE001 — surface, keep going
            print(f"  ✗ {name}: {exc}", file=sys.stderr)
            failed += 1
            continue
        data = _scrub(data)  # neutralize any absolute archive_root path
        if dry_run:
            print(f"  · {name}: {json.dumps(data, ensure_ascii=False)[:120]}…")
        else:
            write_fixture(name, data)
    return failed


# ── Phase 2: studio (session console) fixtures ────────────────────────────────
# The live studio_cli output embeds real absolute paths (``/Volumes/.../
# Livehouse_Archive/2026-06-18/...``) and date-based session names. Those are
# private, so before committing we anonymize: session_key → "Session NN",
# every archive path → an opaque ``/archive/session-NN/...`` token, and every
# featured-frame image → one of the bundled EXIF-stripped demo photos.
DEMO_IMAGE_COUNT = 12  # web/public/demo/demo-01.jpg … demo-12.jpg


def _build_session_map(*key_sources: list) -> tuple[dict, dict]:
    """Return (label_map, slug_map): real session_key → "Session NN" / "session-NN"."""
    keys: set[str] = set()
    for src in key_sources:
        keys.update(k for k in src if k)
    ordered = sorted(keys)  # chronological (keys are ISO dates)
    label_map = {k: f"Session {i + 1:02d}" for i, k in enumerate(ordered)}
    slug_map = {k: f"session-{i + 1:02d}" for i, k in enumerate(ordered)}
    return label_map, slug_map


def _display_date_from_key(session_key: str) -> str:
    sk = str(session_key or "").strip()
    if len(sk) >= 10 and sk[4:5] == "-" and sk[7:8] == "-":
        return sk[:10]
    return ""


def _load_cover_catalog() -> dict[str, dict]:
    """Optional band/date from covers manifest (slug → meta)."""
    man = REPO_ROOT / "web" / "public" / "showcase" / "covers" / "manifest.json"
    if not man.is_file():
        return {}
    try:
        data = json.loads(man.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    out: dict[str, dict] = {}
    for c in data.get("covers") or []:
        if not isinstance(c, dict):
            continue
        slug = str(c.get("slug") or "").strip()
        if slug:
            out[slug] = c
    return out


def _anon_session_obj(
    obj: dict,
    label_map: dict,
    slug_map: dict,
    cover_meta: dict[str, dict] | None = None,
) -> dict:
    """Anonymize one session-shaped dict in place-ish (returns a new dict)."""
    key = obj.get("session_key") or ""
    slug = slug_map.get(key, "session-xx")
    out = dict(obj)
    if "session_key" in out:
        out["session_key"] = label_map.get(key, "Session")
    if "session_dir" in out:
        out["session_dir"] = f"/archive/{slug}"
    if "previews_dir" in out:
        out["previews_dir"] = f"/archive/{slug}/Previews"
    if "raw_dir" in out:
        out["raw_dir"] = f"/archive/{slug}/RAW"
    # Prefer covers written by build_session_covers.py (manifest path / path_portrait).
    # Never keep live absolute archive paths — Vercel has no /Volumes tree.
    meta = (cover_meta or {}).get(slug) or {}
    cover = str(meta.get("path") or "").strip()
    cover_p = str(meta.get("path_portrait") or "").strip()
    if cover.startswith("/showcase/covers/") and cover.endswith(".jpg"):
        out["cover_path_quoted"] = cover
    elif cover_p.startswith("/showcase/covers/") and cover_p.endswith(".jpg"):
        # Portrait-only sessions: use portrait as the default cover too.
        out["cover_path_quoted"] = cover_p
    else:
        # Fallback when covers have not been built yet.
        out["cover_path_quoted"] = f"/showcase/covers/{slug}.jpg"
    if cover_p.startswith("/showcase/covers/") and cover_p.endswith(".jpg"):
        out["cover_portrait_path_quoted"] = cover_p
    else:
        out.pop("cover_portrait_path_quoted", None)
    # Prefer catalog date/band; else keep YYYY-MM-DD parsed from the real key.
    date = str(meta.get("date") or "").strip() or _display_date_from_key(key)
    if date:
        out["session_date"] = date
    band = str(meta.get("band") or meta.get("band_name") or "").strip()
    if band:
        out["band_name"] = band
    venue = str(meta.get("venue") or "").strip()
    if venue:
        out["venue"] = venue
    return out


def _remap_previews(previews_dir: str, key: str, slug_map: dict) -> str:
    return f"/archive/{slug_map.get(key, 'session-xx')}/Previews"


def export_studio(dry_run: bool) -> int:
    print("Exporting studio fixtures from local data (anonymized):")
    failed = 0
    try:
        sessions = run_cli("sessions", ["--limit", "500"])
    except Exception as exc:  # noqa: BLE001
        print(f"  ✗ studio-sessions: {exc}", file=sys.stderr)
        return 1

    session_keys = [s.get("session_key", "") for s in sessions.get("sessions", [])]
    active_key = (sessions.get("active") or {}).get("session_key", "")
    delivery_keys = [d.get("session_key", "") for d in sessions.get("recent_deliveries", [])]
    label_map, slug_map = _build_session_map(session_keys, [active_key], delivery_keys)
    cover_meta = _load_cover_catalog()

    # Pick a representative analyzed session for status + featured-frames.
    rep = None
    if (sessions.get("active") or {}).get("has_analysis_results"):
        rep = sessions["active"]
    if rep is None:
        rep = next(
            (s for s in sessions.get("sessions", []) if s.get("has_analysis_results")),
            None,
        )
    rep_previews = (rep or {}).get("previews_dir", "")

    # 1) studio-sessions — anonymize list + active + recent_deliveries.
    anon_sessions = {
        "archive_root": "/archive",
        "count": sessions.get("count", 0),
        "sessions": [
            _anon_session_obj(s, label_map, slug_map, cover_meta) for s in sessions.get("sessions", [])
        ],
        "active": _anon_session_obj(sessions["active"], label_map, slug_map, cover_meta)
        if sessions.get("active")
        else None,
        "recent_deliveries": [
            {
                **{k: v for k, v in d.items() if k not in ("previews_dir",)},
                "session_key": label_map.get(d.get("session_key", ""), "Session"),
                "previews_dir": _remap_previews(d.get("previews_dir", ""), d.get("session_key", ""), slug_map),
                "session_date": (
                    str((cover_meta.get(slug_map.get(d.get("session_key", ""), ""), {}) or {}).get("date") or "").strip()
                    or d.get("session_date")
                    or _display_date_from_key(str(d.get("session_key") or ""))
                ),
            }
            for d in sessions.get("recent_deliveries", [])
        ],
    }

    fixtures: list[tuple[str, dict]] = [("studio-sessions", anon_sessions)]

    # 2) studio-status — representative pipeline snapshot for any selected session.
    if rep_previews:
        try:
            status = run_cli("status", [rep_previews])
            for field in ("active", "session"):
                if isinstance(status.get(field), dict):
                    status[field] = _anon_session_obj(status[field], label_map, slug_map, cover_meta)
            if "archive_root" in status:
                status["archive_root"] = "/archive"
            fixtures.append(("studio-status", status))
        except Exception as exc:  # noqa: BLE001
            print(f"  ✗ studio-status: {exc}", file=sys.stderr)
            failed += 1

        # 3) studio-featured-frames — swap real photo paths for bundled demo images.
        try:
            ff = run_cli("featured-frames", [rep_previews])
            frames = ff.get("frames", [])[:6]
            for i, fr in enumerate(frames):
                n = (i % DEMO_IMAGE_COUNT) + 1
                fr["path_quoted"] = f"demo-{n:02d}.jpg"
                fr["file"] = f"frame-{i + 1:02d}.jpg"
            fixtures.append((
                "studio-featured-frames",
                {"previews_dir": "/archive/session-featured/Previews", "frames": frames, "count": len(frames)},
            ))
        except Exception as exc:  # noqa: BLE001
            print(f"  ✗ studio-featured-frames: {exc}", file=sys.stderr)
            failed += 1

    # 4) studio-infra-overview — no paths, safe as-is.
    try:
        fixtures.append(("studio-infra-overview", run_cli("infra-overview", [])))
    except Exception as exc:  # noqa: BLE001
        print(f"  ✗ studio-infra-overview: {exc}", file=sys.stderr)
        failed += 1

    for name, data in fixtures:
        data = _scrub(data)  # final path/hostname safety net
        if dry_run:
            print(f"  · {name}: {json.dumps(data, ensure_ascii=False)[:120]}…")
        else:
            write_fixture(name, data)
    return failed


# ── Phase 3: infra console fixtures ───────────────────────────────────────────
# The /infra dashboard polls ~14 FastAPI endpoints that have no Next route
# handler (they proxy to FastAPI in full mode). We snapshot each endpoint's real
# response in-process via FastAPI's TestClient — real routing + response_model
# serialization — then scrub paths/hostnames. Requires ``fastapi`` installed;
# import lazily so landing/studio export still works without it.
#
# (URL path, query string, fixture name). Drill-downs use one representative id.
INFRA_ENDPOINTS: list[tuple[str, str, str]] = [
    ("metrics", "", "infra-metrics"),
    ("metrics/history", "window_sec=3600&limit=240", "infra-metrics-history"),
    ("workers", "", "infra-workers"),
    ("providers", "", "infra-providers"),
    ("cost", "", "infra-cost"),
    ("dead-letter", "limit=15&offset=0", "infra-dead-letter"),
    ("runtime-stream", "events_limit=80", "infra-runtime-stream"),
    ("brain", "sessions_limit=15&photos_limit=30", "infra-brain"),
    ("agent/runs", "limit=8", "infra-agent-runs"),
    ("jobs", "limit=100&offset=0", "infra-jobs"),
]


def export_infra(dry_run: bool) -> int:
    print("Exporting infra console fixtures from local data (anonymized):")
    try:
        from fastapi import FastAPI
        from fastapi.testclient import TestClient

        sys.path.insert(0, str(REPO_ROOT))
        from api.infra_routes import router  # noqa: E402
    except Exception as exc:  # noqa: BLE001
        print(f"  ✗ infra export skipped (need `pip install fastapi httpx`): {exc}", file=sys.stderr)
        return 1

    app = FastAPI()
    app.include_router(router)
    client = TestClient(app)
    failed = 0

    def dump(path: str, query: str, name: str) -> dict | None:
        url = f"/api/infra/{path}" + (f"?{query}" if query else "")
        res = client.get(url)
        if res.status_code != 200:
            print(f"  ✗ {name}: HTTP {res.status_code} {url}", file=sys.stderr)
            return None
        data = _scrub(res.json())
        if dry_run:
            print(f"  · {name}: {json.dumps(data, ensure_ascii=False)[:110]}…")
        else:
            write_fixture(name, data)
        return data

    for path, query, name in INFRA_ENDPOINTS:
        try:
            data = dump(path, query, name)
            if data is None:
                failed += 1
        except Exception as exc:  # noqa: BLE001
            print(f"  ✗ {name}: {exc}", file=sys.stderr)
            failed += 1

    # Representative drill-downs: pick the newest job id (+ its trace) from the list.
    job_id = None
    trace_id = None
    try:
        jobs = client.get("/api/infra/jobs?limit=1&offset=0").json()
        items = jobs.get("items") or []
        if items:
            job_id = items[0].get("id")
            trace_id = items[0].get("trace_id")
    except Exception:  # noqa: BLE001
        pass

    if job_id is not None:
        for path, name in [
            (f"jobs/{job_id}", "infra-job-detail"),
            (f"jobs/{job_id}/stages", "infra-job-stages"),
            (f"jobs/{job_id}/timeline", "infra-job-timeline"),
        ]:
            try:
                if dump(path, "", name) is None:
                    failed += 1
            except Exception as exc:  # noqa: BLE001
                print(f"  ✗ {name}: {exc}", file=sys.stderr)
                failed += 1
    if trace_id:
        try:
            if dump(f"traces/{trace_id}", "", "infra-trace") is None:
                failed += 1
        except Exception as exc:  # noqa: BLE001
            print(f"  ✗ infra-trace: {exc}", file=sys.stderr)
            failed += 1

    return failed


def main() -> int:
    parser = argparse.ArgumentParser(description="Export the Vercel showcase snapshot.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be exported without writing fixtures.",
    )
    args = parser.parse_args()

    failed = export_landing(args.dry_run)
    failed += export_studio(args.dry_run)
    failed += export_infra(args.dry_run)

    if failed:
        print(f"\nDone with {failed} failure(s).", file=sys.stderr)
        return 1
    print("\nDone. Commit web/fixtures/ (and web/public/showcase/ once step 2 lands).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
